package com.ackileo.telematics.data.repository
import com.ackileo.telematics.data.remote.models.TripResponse
import com.ackileo.telematics.data.local.dao.DriverDao
import com.ackileo.telematics.data.local.entities.TripEntity
import com.ackileo.telematics.data.remote.ApiService
import com.ackileo.telematics.data.remote.models.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton
import com.ackileo.telematics.data.remote.models.TripSummary
/**
 * Repository Interface defining Trip operations.
 * Handles the data strategy (Network + Local Cache).
 */
interface TripRepository {
    suspend fun startTrip(request: TripStartRequest): Result<TripResponse>
    suspend fun endTrip(request: TripEndRequest): Result<TripResponse>
    suspend fun sendEvent(request: EventRequest): Result<Unit>
    fun getTripHistory(): Flow<List<TripSummary>>
    suspend fun refreshTrips(): Result<Unit>
}

@Singleton
class TripRepositoryImpl @Inject constructor(
    private val apiService: ApiService,
    private val driverDao: DriverDao

) : TripRepository {

    /**
     * Start a trip via API.
     */
    override suspend fun startTrip(request: TripStartRequest): Result<TripResponse> =
        withContext(Dispatchers.IO) {
            runCatching { apiService.startTrip(request) }
        }

    /**
     * End a trip via API and immediately cache the result to Room.
     */
    override suspend fun endTrip(request: TripEndRequest): Result<TripResponse> =
        withContext(Dispatchers.IO) {
            runCatching {
                val response = apiService.endTrip(request)
                // Cache the finished trip details locally
                driverDao.insertTrip(response.toEntity())
                response
            }
        }

    /**
     * Send telematics events (harsh braking, speeding) to the server.
     */
    override suspend fun sendEvent(request: EventRequest): Result<Unit> =
        withContext(Dispatchers.IO) {
            runCatching {
                apiService.sendEvent(request)
                Unit
            }
        }

    /**
     * Provides a reactive stream of trips from the local database.
     * FIX: Explicitly typed 'entities: List<TripEntity>' to resolve inference error.
     */
    override fun getTripHistory(): Flow<List<TripSummary>> =
        driverDao.getRecentTrips()
            .distinctUntilChanged()
            .map { entities: List<TripEntity> ->
                entities.map { it.toDomainModel() }
            }

    /**
     * Synchronizes local storage with the remote API.
     * FIX: Explicitly typed 'trip: TripResponse' in map to resolve inference error.
     */
    override suspend fun refreshTrips(): Result<Unit> =
        withContext(Dispatchers.IO) {
            runCatching {
                val response: List<TripResponse> = apiService.getTrips()

                // Explicitly define the mapping to avoid type inference issues
                val entities = response.map { trip: TripResponse ->
                    trip.toEntity()
                }

                // Atomic database update
                driverDao.refreshTrips(entities)
                Unit
            }
        }
}

/**
 * Mapper: Database Entity -> Domain Model (UI Model)
 */
private fun TripEntity.toDomainModel(): TripSummary = TripSummary(
    startTime = this.startTime,
    endTime = this.endTime,
    totalDistanceKm = this.totalDistanceKm,
    averageSpeedKmh = this.averageSpeedKmh,
    durationMinutes = this.durationMinutes,
    safetyScore = this.safetyScore
)

/**
 * Mapper: Network Response -> Database Entity
 */
private fun TripResponse.toEntity(): TripEntity = TripEntity(
    startTime = this.startTime?.toLongOrNull() ?: 0L,
    endTime = this.endTime?.toLongOrNull() ?: 0L,
    // Note: Primary Key 'id' is auto-generated by Room

    totalDistanceKm = this.totalDistance ?: 0.0,
    averageSpeedKmh = this.averageSpeed ?: 0.0,
    durationMinutes = this.duration ?: 0,
    safetyScore = this.safetyScore ?: 0.0,
    destination = this.destination ?: "Unknown Destination"
)